### ISSUE TITLE
Put up a search box for city based event search

### ISSUE THREAD

**Issue by dolftax** [MozillaIndia/old-vibe#34]
Ref - http://dpaste.com/2Q3YSSN

When searched for `Bangalore`, check with locally fetched data and display it. Notice the `City` key.

**Comment by dolftax** [comment]
Assigning to @tsl143

**Comment by dolftax** [comment]
Done!

**Comment by AkhilHector** [comment]
@dolftax  @tsl143 we must ensure the search text is mapped to all cases
